/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'timothy' at '11/10/16 10:05 PM' with Gradle 2.14.1
 *
 * @author timothy, @date 11/10/16 10:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
